name: Terraform AWS CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  

env:
  TF_VERSION: "1.11.4"
  AWS_REGION: "us-east-1"  # Change to your region
  TF_PATH: infra

jobs:
  terraform:
    name: Terraform Format, Validate, Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_PATH }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.TF_PATH }}  
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ env.TF_PATH }}
        run: terraform validate

      - name: access test
        run: aws s3 ls s3://terraform-hcl-test-state/terraform.tfstate --region us-east-1

      - name: Terraform Plan
        working-directory: ${{ env.TF_PATH }}
        run: |
          terraform plan -out=tfplan --var-file=dev.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_PATH }}
        run: terraform apply -auto-approve tfplan --var-file=dev.tfvars
